default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sagebadger_development

test:
  <<: *default
  database: sagebadger_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cache_migrate
    pool: <%= ENV.fetch("DB_POOL_CACHE", 2) %>
  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/queue_migrate
    pool: <%= ENV.fetch("DB_POOL_QUEUE", 8) %>
  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cable_migrate
    pool: <%= ENV.fetch("DB_POOL_CABLE", 2) %>
